# Generated by Django 5.0.2 on 2024-02-11 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0003_alter_surveyresults_advancement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='sessions',
            name='closing_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sessions',
            name='opening_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
