# Generated by Django 5.0.2 on 2024-02-11 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0005_alter_sessions_closing_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='closing_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='opening_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
